### PR TITLE
wrapped most of the osgEarth related classes

### PR DESCRIPTION
**Pull request by devcxx**
hope you can sort it out @podsvirov

### CODE REVIEW

**Comment by podsvirov** [comment]
A great job, thank you for your efforts!

It seems to me that you are a kind and cheerful person... The process of reviewing your changes will take some time :-) (I am engaged in this project in my spare time, and I do not have much of it).

**Comment by devcxx** [comment]
thanks, you do a great job too :) , by the way  hope you can solve #13 issues

**Comment by podsvirov** [comment]
@devcxx, you did a lot of work, but how did you test the performance of your code? The osgQtQuick project uses a CMake building system. In your changes there is only the `*.pri` files and not any `CMakeLists.txt` modifications.
Nevertheless, if you somehow built it, do you have any examples of scripts for manual checking, like a `tests/earth.qml` file?

**Comment by devcxx** [comment]
ok, i will pull some examples of qml file soon

**Pull request closed without merging**
